---
output: rmarkdown::github_document
---

`warc` : Tools to Work with the Web Archive Ecosystem

The following functions are implemented:

- `expand`:	Expand a compressed raw buffer
- `read_cdx`:	Read a WARC CDX index file
- `read_warc_entry`:	Read a WARC entry from a WARC file
- `warc_headers`:	Extract WARC headers from a WARC response object

### Installation

```{r eval=FALSE}
devtools::install_github("hrbrmstr/warc")
```

```{r echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
options(width=120)
```

### Usage

```{r message=FALSE, warning=FALSE}
library(warc)
library(httr)

# current verison
packageVersion("warc")

cdx <- read_cdx(system.file("extdata", "20160901.cdx", package="warc"))

i <- 5

p <- file.path(cdx$warc_path[i], cdx$file_name[i])
st <- cdx$compressed_arc_file_offset[i]
sz <- cdx$calc_compressed_warc_rec_size[i]

entry <- read_warc_entry(p, st, sz)

print(entry)

print(warc_headers(entry))

print(status_code(entry))

print(http_type(entry))
```

### Test Results

```{r message=FALSE, warning=FALSE}
library(warc)
library(testthat)

date()

test_dir("tests/")
```

