// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// int_create_cdx_from_gzwarc
void int_create_cdx_from_gzwarc(std::string warc_path, std::string warc_record_types, std::string field_spec, std::string cdx_path);
RcppExport SEXP warc_int_create_cdx_from_gzwarc(SEXP warc_pathSEXP, SEXP warc_record_typesSEXP, SEXP field_specSEXP, SEXP cdx_pathSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type warc_path(warc_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type warc_record_types(warc_record_typesSEXP);
    Rcpp::traits::input_parameter< std::string >::type field_spec(field_specSEXP);
    Rcpp::traits::input_parameter< std::string >::type cdx_path(cdx_pathSEXP);
    int_create_cdx_from_gzwarc(warc_path, warc_record_types, field_spec, cdx_path);
    return R_NilValue;
END_RCPP
}
// inflate_from_pos
RawVector inflate_from_pos(std::string src, size_t raw_stream_pos);
RcppExport SEXP warc_inflate_from_pos(SEXP srcSEXP, SEXP raw_stream_posSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type src(srcSEXP);
    Rcpp::traits::input_parameter< size_t >::type raw_stream_pos(raw_stream_posSEXP);
    __result = Rcpp::wrap(inflate_from_pos(src, raw_stream_pos));
    return __result;
END_RCPP
}
// gzuncompress
SEXP gzuncompress(SEXP r_source, SEXP r_guess_size);
RcppExport SEXP warc_gzuncompress(SEXP r_sourceSEXP, SEXP r_guess_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type r_source(r_sourceSEXP);
    Rcpp::traits::input_parameter< SEXP >::type r_guess_size(r_guess_sizeSEXP);
    __result = Rcpp::wrap(gzuncompress(r_source, r_guess_size));
    return __result;
END_RCPP
}
// find_sequence
int find_sequence(RawVector buffer, RawVector pattern);
RcppExport SEXP warc_find_sequence(SEXP bufferSEXP, SEXP patternSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< RawVector >::type buffer(bufferSEXP);
    Rcpp::traits::input_parameter< RawVector >::type pattern(patternSEXP);
    __result = Rcpp::wrap(find_sequence(buffer, pattern));
    return __result;
END_RCPP
}
