field_trans <-
  structure(
    list(
      field = c(
        "A",
        "B",
        "C",
        "D",
        "F",
        "G",
        "H",
        "I",
        "J",
        "K",
        "L",
        "M",
        "N",
        "P",
        "Q",
        "R",
        "S",
        "U",
        "V",
        "X",
        "Y",
        "Z",
        "a",
        "b",
        "c",
        "d",
        "e",
        "f",
        "g",
        "h",
        "i",
        "j",
        "k",
        "l",
        "m",
        "n",
        "o",
        "p",
        "r",
        "s",
        "t",
        "u",
        "v",
        "x",
        "y",
        "z"
      ),
      short_name = c(
        "canonized_url",
        "news_group",
        "rulespace_category",
        "compressed_dat_file_offset",
        "canonized_Frame",
        "multi_column_lang_desc",
        "canonized_host",
        "canonized_image",
        "canonized_jump_point",
        "fbis",
        "canonized_link",
        "meta_tags",
        "massaged_url",
        "canonized_path",
        "language_string",
        "canonized_redirect",
        "compressed_record_size",
        "uniqueness",
        "compressed_arc_file_offset",
        "canonized_url_href",
        "canonized_url_src",
        "canonized_url_script",
        "original_url",
        "date",
        "old_style_checksum",
        "uncompressed_dat_file_offset",
        "ip",
        "frame",
        "file_name",
        "original_host",
        "image",
        "original_jump_point",
        "new_style_checksum",
        "link",
        "mime_type_orig",
        "arc_document_length",
        "port",
        "original_path",
        "redirect",
        "response_code",
        "title",
        "urn",
        "uncompressed_arc_file_offset",
        "url_href",
        "url_src",
        "url_script"
      ),
      description = c(
        "canonized url",
        "news group",
        "rulespace category",
        "compressed dat file offset",
        "canonized frame",
        "multi-columm language description",
        "canonized host",
        "canonized image",
        "canonized jump point",
        "Some weird FBIS whats changed kinda thing",
        "canonized link",
        "meta tags (AIF)",
        "massaged url",
        "canonized path",
        "language string",
        "canonized redirect",
        "compressed record size",
        "uniqness",
        "compressed arc file offset",
        "canonized url in other href tages",
        "canonized url in other src tags",
        "canonized url found in script",
        "original url",
        "date",
        "old style checksum",
        "uncompressed dat file offset",
        "IP",
        "frame",
        "file name",
        "original host",
        "image",
        "original jump point",
        "new style checksum",
        "link",
        "mime type of original document",
        "arc document length",
        "port",
        "original path",
        "redirect",
        "response code",
        "title",
        "warc record id",
        "uncompressed arc file offset",
        "url in other href tages",
        "url in other src tags",
        "url found in script"
      )
    ),
    .Names = c("field", "short_name", "description"),
    row.names = c(NA, -46L),
    class = c("tbl_df", "tbl", "data.frame")
  )